version: "3.8"

services:
  spring-v2:
    container_name: spring_v2
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - redis_v2
    networks:
      - templenet

  redis_v2:
    image: redis:7.2
    container_name: redis_v2
    restart: always
    command: redis-server --requirepass ${SPRING_REDIS_PASSWORD}
    ports:
      - "6380:6379" # (선택) 외부 접근 위해 열어두는 경우
    networks:
      - templenet

networks:
  templenet:
    external: true