version: '3.8'

services:
  spring-v2:
    container_name: spring_v2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - templenet

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    command: redis-server --requirepass ${SPRING_REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - templenet

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - templenet

networks:
  templenet:
    external: true