version: '3.8'

services:
  spring-v2:
    container_name: spring_v2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - sopt-jeolloga_templenet

networks:
  sopt-jeolloga_templenet:
    external: true

