version: "3.8"

services:
  spring-v2:
    container_name: spring_v2
    build:
      context: .
    env_file:
      - .env
    environment:
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
    ports:
      - "8081:8080"
    depends_on:
      - redis_v2
    networks:
      - templenet

  redis_v2:
    image: redis:7.2
    container_name: redis_v2
    restart: always
    command: redis-server --requirepass ${SPRING_DATA_REDIS_PASSWORD}
    networks:
      - templenet

networks:
  templenet:
    external: true