spring:
  datasource:
    url: jdbc:mysql://jeolloga-database.crwyiaesc6os.ap-northeast-2.rds.amazonaws.com:3306/newjeolloga
    username: root
    password: jeolloga1221
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: info
    sopt.jeolloga: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

kakao:
  client:
    client-id: 350e48505b8985851a292bc14b4b6652
    admin-key: eb39339ae43bc5329356e7b3c3971493
    client-secret: kgc3xRyse3amHz5aTwrmdLBtT5I3yYky
    client-authentication-method: client_secret_post
    authorization-grant-type: authorization_code
    scope:
      - profile_nickname
      - account_email

jwt:
  secret: MinjeongDajinSeonghuiTaewookAyoungHoyoungGahyeonGayoonSoyoungSeunghyunYoungkeongYoumin
  access-expiration: 3600
  refresh-expiration: 1209600
  kakao-expiration: 3600