spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: info
    sopt.jeolloga: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

geocoding:
  api:
    key: ${GEOCODING_API_KEY}

kakao:
  client:
    client-id: ${KAKAO_CLIENT_ID}
    admin-key: ${KAKAO_ADMIN_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}
    client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
    authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    scope:
      - profile_nickname
      - account_email

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  kakao-expiration: ${JWT_KAKAO_EXPIRATION}